apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-ubuntu-slave 
  namespace: devops-tools
  labels:
    app: jenkins-ubuntu-slave
spec:
  selector:
    matchLabels:
      app: jenkins-ubuntu-slave
  
  template:
    metadata:
      labels:
        app: jenkins-ubuntu-slave
    
    spec:
      serviceAccountName: jenkins-admin
      automountServiceAccountToken: true
      securityContext:
          fsGroup: 0
          runAsUser: 0
      containers:
      - name: jenkins-ubuntu-slave
        imagePullPolicy: Always
        image: kareemelkasaby/jenkins-slave-java-11
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 22
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
